config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  root to: "tickets#index"

  get "admins", to: "admins/reservations#index", as: :admin_root # ログイン後に遷移するためにasオプションを追加
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
end

app/controllers/admins/reservations_controller.rb
class Admins::ReservationsController < Admins::ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/reservations/index.html.haml
%h1 予約一覧
= button_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600'

app/views/admins/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation{ 'data-turbo-cache': 'false' }
    %h2
      = I18n.t 'errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/admins/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to t devise.shared.sign_in, new_session_path(resource_name)
  %br

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t devise.shared.sign_up, new_registration_path(resource_name)
  %br

- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t devise.shared.forgot_your_password, new_password_path(resource_name)
  %br

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t devise.shared.didn_t_receive_confirmation_instructions, new_confirmation_path(resource_name)
  %br

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t devise.shared.didn_t_receive_unlock_instructions, new_unlock_path(resource_name)
  %br

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = button_to t(devise.shared.sign_in_with_provider, provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider), data: { turbo: false }
    %br

app/views/layouts/_head.html.haml
%head
  %title= title
  %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1' }
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
  = stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
  = javascript_importmap_tags

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head', title: 'PeachClone'
  %body
    = yield
    - if flash.any?
      .fixed.bottom-8.left-4.py-2.px-8.rounded.bg-slate-300
        - flash.each do |_, message|
          %p.py-2= message

app/views/tickets/index.html.haml
%h1 トップページ